- platform: google_travel_time
  name: Port autority to home (Car)
  api_key: !secret google_api_key
  origin: !secret port_authority_address
  destination: zone.home
  options: 
    mode: transit