- platform: yr
# sensor 2
- platform: cpuspeed
# sensor 3
- platform: time_date
  display_options:
    - "date_time"
# sensor ip
- platform: dnsip
# pi hole
- platform: pi_hole
  host: 192.168.0.24
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
# sensor for home automation version
- platform: rest
  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
  username: !secret github_username
  password: !secret gitgub_password
  authentication: basic
  value_template: '{{ value_json.tag_name }}'
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor