- platform: alpha_vantage
  api_key: !secret alpha_vantage_api_key
  scan_interval: 30
  symbols: 
    - symbol: GOOGL
      currency: USD
    - symbol: GOOG
      currency: USD
    - symbol: MSFT
      currency: USD
    - symbol: GE
      currency: USD
    - symbol: UPS
      currency: USD
    - symbol: DAL
      currency: USD
