- platform: rest
  name: INR
  resource: https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=usd&to_currency=inr&apikey=!secret alpha_vantage_api_key
  value_template: '{{ value_json["Realtime Currency Exchange Rate"]["5. Exchange Rate"]}}'
  