- platform: command_line
  name: Miner Stats Local
  command: !secret miner_getstat1  
  value_template: '{{ value_json.result }}'
  
- platform: template
  sensors:
    miner_online_time:
      friendly_name: 'Online Since'
      value_template: >- 
        {%  set miner_online_min = states.sensor.miner_online_local.state | int %}
        {% if (miner_online_min // 1440 > 0) -%}
          {{ miner_online_min // 1440 }} day
          {{ miner_online_min % 1440 // 60}} hours
        {%- else %}
        {% if (miner_online_min // 60 > 0) -%}
          {{ miner_online_min // 60 }} hours
        {%- endif %}
        {%- endif %}
        {{ miner_online_min % 60 }} min
      unit_of_measurement: ""
    miner_online_local:
      friendly_name: 'Online'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[1] | replace(\"'\", \"\") }}"
      unit_of_measurement: min
    hashrate_local:
      friendly_name: 'Current Hashrate'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[2].split(';')[0] | replace(\"'\", \"\") | multiply(0.001) | round(1)}}"
      unit_of_measurement: mh
    valid_shares_local:
      friendly_name: 'Valid Shares'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[2].split(';')[1] | replace(\"'\", \"\")}}"
      unit_of_measurement: int
    rejected_shares_local:
      friendly_name: 'Rejected Shares'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[2].split(';')[2] | replace(\"'\", \"\")}}"
      unit_of_measurement: int
    gpu0_hashrate_local:
      friendly_name: 'GPU 0 Hashrate'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[3].split(';')[0] | replace(\"'\", \"\") | multiply(0.001) | round(1)}}"
      unit_of_measurement: mh
    gpu1_hashrate_local:
      friendly_name: 'GPU 1 Hashrate'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[3].split(';')[1] | replace(\"'\", \"\") | multiply(0.001) | round(1)}}"
      unit_of_measurement: mh
    gpu2_hashrate_local:
      friendly_name: 'GPU 2 Hashrate'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[3].split(';')[2] | replace(\"'\", \"\") | multiply(0.001) | round(1)}}"
      unit_of_measurement: mh
    gpu0_temp_local:
      friendly_name: 'GPU 0 temp'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[6].split(';')[0] | replace(\"'\", \"\")}}"
      unit_of_measurement: "C"
    gpu0_fan_local:
      friendly_name: 'GPU 0 fan speed'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[6].split(';')[1] | replace(\"'\", \"\")}}"
      unit_of_measurement: "%"
    gpu1_temp_local:
      friendly_name: 'GPU 1 temp'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[6].split(';')[2] | replace(\"'\", \"\")}}"
      unit_of_measurement: "C"
    gpu1_fan_local:
      friendly_name: 'GPU 1 fan speed'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[6].split(';')[3] | replace(\"'\", \"\")}}"
      unit_of_measurement: "%"
    gpu2_temp_local:
      friendly_name: 'GPU 2 temp'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[6].split(';')[4] | replace(\"'\", \"\")}}"
      unit_of_measurement: "C"
    gpu2_fan_local:
      friendly_name: 'GPU 2 fan speed'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[6].split(';')[5] | replace(\"'\", \"\")}}"
      unit_of_measurement: "%"
    mining_pool:
      friendly_name: 'current mining pool'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[7]| replace(\"'\", \"\")}}"
      unit_of_measurement: ""
    invalid_shares_local:
      friendly_name: 'Invalid Shares'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[8].split(';')[0]| replace(\"'\", \"\")}}"
      unit_of_measurement: int
    pool_switches:
      friendly_name: 'Pool Switches'
      value_template: "{{ states.sensor.miner_stats_local.state.split(',')[8].split(';')[1]| replace(\"'\", \"\")}}"
      unit_of_measurement: int
  