- platform: njtransit
  name: 114X to city
  route: 114
  direction: New%20York
  stop_id: 29653

- platform: njtransit
  name: 117 to city
  route: 117
  direction: New%20York
  stop_id: 29653

- platform: njtransit
  name: 114-local to city
  route: 114
  direction: New%20York
  stop_id: 31398

# - platform: njtransit
#   name: 190 to city
#   route: 190
#   direction: New%20York
#   stop_id: 21625

# - platform: njtransit
#   name: 122 to city (first st)
#   route: 122
#   direction: New%20York
#   stop_id: 21609

# - platform: njtransit
#   name: 122 to city (Mapple st)
#   route: 122
#   direction: New%20York
#   stop_id: 21608

# - platform: njtransit
#   name: 122 to city (GOLDEN AVE)
#   route: 122
#   direction: New%20York
#   stop_id: 21570

# - platform: njtransit
#   name: 122 to home 
#   route: 122
#   direction: Secaucus
#   stop_id: 26229

# - platform: njtransit
#   name: 190 to home 
#   route: 190
#   direction: paterson
#   stop_id: 26229