- platform: generic
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?num=6&type=N0R&mapx=400&mapy=240&brand=wui&delay=25&frame=0&scale=1&transx=0&transy=0&severe=1&smooth=0&centerx=400&centery=240&station=OKX&rainsnow=0&lightning=0&noclutter=0&showlabels=1&showstorms=99&rand=25961627
  name: Radar
